module.exports = (sequelize, DataTypes) => {
  const DataCore = sequelize.define(
    "data_core",
    {
      kdcab: DataTypes.STRING,
      nama: DataTypes.STRING,
      namaktp: DataTypes.STRING,
      tempatlahir: DataTypes.STRING,
      tanggallahir: DataTypes.DATEONLY,
      umur: DataTypes.INTEGER,
      lokasiusaha: DataTypes.STRING,
      kota: DataTypes.STRING,
      alamat: DataTypes.TEXT,
      kodepos: DataTypes.STRING(10),
      kelurahan: DataTypes.STRING,
      kecamatan: DataTypes.STRING,
      pendidikan: DataTypes.STRING,
      ktp: DataTypes.STRING(20),
      sim: DataTypes.STRING(20),
      npwp: DataTypes.STRING(25),
      statuspernikahan: DataTypes.STRING,
      jeniskelamin: DataTypes.STRING(20),
      nomortelepon: DataTypes.STRING(20),
      nohp: DataTypes.STRING(20),
      email: DataTypes.STRING,
      namaibu: DataTypes.STRING,
      statusrumah: DataTypes.STRING,
      katdeb: DataTypes.STRING,
      katdebnm: DataTypes.STRING,
      goldeb: DataTypes.STRING,
      goldebnm: DataTypes.STRING,
      kodemo: DataTypes.STRING,
      namamo: DataTypes.STRING,
      usrid: DataTypes.STRING,
      jenispekerjaan: DataTypes.STRING,
      kodepekerjaan: DataTypes.STRING,
      namaperusahaan: DataTypes.STRING,
      kodeposperusahaan: DataTypes.STRING(10),
      alamatusaha: DataTypes.TEXT,
      namakontak: DataTypes.STRING,
      jeniskelaminkontak: DataTypes.STRING(20),
      hubungankeluarga: DataTypes.STRING,
      alamatkontak: DataTypes.TEXT,
      kodeposkontak: DataTypes.STRING(10),
      nohpkontak: DataTypes.STRING(20),
      namapasangan: DataTypes.STRING,
      namapanggilan: DataTypes.STRING,
      ktppasangan: DataTypes.STRING(20),
      tempatlahirpasangan: DataTypes.STRING,
      nohppasangan: DataTypes.STRING(20),
      plafond: DataTypes.DECIMAL(15, 2),
      kodeproduk: DataTypes.STRING,
      kolekbi: DataTypes.STRING,
      tujuanpenggunaan: DataTypes.STRING,
      tglpermohonan: DataTypes.DATEONLY,
      jangkawaktu: DataTypes.INTEGER,
      tanggalawal: DataTypes.DATEONLY,
      rumusbunga: DataTypes.STRING,
      metodeangsur: DataTypes.STRING,
      baserate: DataTypes.DECIMAL(10, 4),
      flat: DataTypes.DECIMAL(10, 4),
    },
    {
      tableName: "data_core",
      schema: "mobile",
      freezeTableName: true,
      timestamps: true, // ✅ AKTIFKAN TIMESTAMP
      createdAt: "created_date", // ✅ map createdAt ke created_date
      updatedAt: "updated_date", // ✅ map updatedAt ke updated_date
    }
  );

  return DataCore;
};
